---
title: "05 Summary Statistics"
author: "Thomas J. Brailey"
date: "1/24/2020"
output:
  pdf_document:
    toc: yes
    keep_tex: yes
  html_notebook:
    toc: yes
    toc_float: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---
<style>
    body .main-container {
        max-width: 100%;
    }
</style>

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
```

# Load and clean data
```{r}
# Load PSP data, created in tjbrailey_wrangle_data.Rmd.
psp <- rio::import(paste0(here::here(), "/data/tjbrailey_psp_clean.csv"))
psp <- psp[,-1]
psp_sub <- psp %>%
  dplyr::select(cown, year, dpi_auton, dpi_author,
                idc_subed, idc_subtax, idc_subpolice,
                polity4_polity_score)

# Regional Autonomy Index
rai <- rio::import(paste0(here::here(), "/data/RAI_country_scores_2015.xlsx")) %>%
  dplyr::select(country_name, year, n_RAI) %>%
  dplyr::mutate(cown = countrycode::countrycode(country_name, "country.name", "cown"),
                year = as.numeric(year)) %>%
  dplyr::select(cown, year, n_RAI)

# Local Autonomy Index
lai <- rio::import(paste0(here::here(), "/data/LAI_data_v6_temp2.sav"))

# Ethnic Power Relations
epr <- rio::import(paste0(here::here(), "/data/EPR-2018.1.1.csv")) %>%
  dplyr::mutate(cown = countrycode::countrycode(gwid, "gwn", "cown")) %>%
  dplyr::select(cown, from, group, reg_aut) %>%
  dplyr::rename(year = from) %>% 
  dplyr::group_by(cown, group) %>%
  tidyr::complete(cown, group, 
                  year = 1946:2017, 
                  fill = list(incidents = 0)) 
epr_wide <- epr %>% 
  tidyr::pivot_wider(names_from = group, 
                     values_from = reg_aut) %>%
  dplyr::group_by(cown) 
epr_wide <- epr_wide %>%
  tidyr::fill_(names(epr_wide[,2:642])) %>%
  dplyr::ungroup()
epr_wide$reg_aut_cont <- rowSums(epr_wide[,3:642] == TRUE, na.rm = TRUE)
epr_final <- epr_wide %>%  
  dplyr::mutate(reg_aut_dum = ifelse(reg_aut_cont >= 1, 1, 0)) %>%
  dplyr::select(cown, year, reg_aut_dum, reg_aut_cont)
```
# Join datasets
```{r}
join1 <- dplyr::left_join(psp_sub, rai, by = c("cown", "year"))
join2 <- dplyr::left_join(join1, epr_final, by = c("cown", "year"))

join2[join2 == -999 |
        join2 == -77 |
        join2 == -44] <- NA

reg_data <- join2 %>%
  dplyr::mutate(dpi_auton = as.logical(dpi_auton),
                dpi_author = as.logical(dpi_author),
                reg_aut_dum = as.logical(reg_aut_dum))
reg_data_complete <- reg_data[complete.cases(reg_data), ] %>%
  dplyr::select(cown, year, 
                dpi_auton, n_RAI, reg_aut_dum, 
                idc_subtax, idc_subed, idc_subpolice, 
                dpi_author, polity4_polity_score
                )
```

# Plot correlation tables
```{r}
auton_cor_pear <- xtable::xtable(round(cor(reg_data_complete[, 3:9]
                                           ), 2)
                                 )
upper <- auton_cor_pear
upper[upper.tri(auton_cor_pear)] <- ""
upper <- as.data.frame(upper)
upper <- xtable::xtable(upper)
upper

auton_cor_spear <- xtable::xtable(round(cor(reg_data_complete[, 3:9], 
                                            method = "spearman"
                                            ), 2)
                                  )
auton_cor_spear
auton_cor_ken <- xtable::xtable(round(cor(reg_data_complete[, 3:9], 
                                          method = "kendall"
                                          ), 2)
                                )
auton_cor_ken
```

# Regressions
```{r}
reg1 <- lm(polity4_polity_score ~ dpi_auton, data = reg_data_complete)
reg1_tex <- texreg::texreg(reg1, include.ci = FALSE)
reg1_tex
plot(x = reg_data_complete$dpi_auton, y = reg_data_complete$polity4_polity_score)
abline(reg = reg1)

reg2 <- lm(polity4_polity_score ~ idc_subtax, data = reg_data_complete)
reg2_tex <- texreg::texreg(reg2, include.ci = FALSE)
reg2_tex
plot(x = reg_data_complete$idc_subtax, y = reg_data_complete$polity4_polity_score)
abline(reg = reg2)

reg3 <- lm(polity4_polity_score ~ idc_subed, data = reg_data_complete)
reg3_tex <- texreg::texreg(reg3, include.ci = FALSE)
reg3_tex
plot(x = reg_data_complete$idc_subed, y = reg_data_complete$polity4_polity_score)
abline(reg = reg3)

reg4 <- lm(polity4_polity_score ~ idc_subpolice, data = reg_data_complete)
reg4_tex <- texreg::texreg(reg4, include.ci = FALSE)
reg4_tex
plot(x = reg_data_complete$idc_subpolice, y = reg_data_complete$polity4_polity_score)
abline(reg = reg4)

reg5 <- lm(polity4_polity_score ~ n_RAI, data = reg_data_complete)
reg5_tex <- texreg::texreg(reg5, include.ci = FALSE)
reg5_tex
jpeg(filename = paste0(here::here(), "/vis/polity_score_rai_reg.jpeg"))
plot(x = reg_data_complete$n_RAI, 
     y = reg_data_complete$polity4_polity_score,
     xlab = "RAI Measure of Autonomy", 
     ylab = "Polity Score", 
     main = "Predicting Polity Score with Regional Autonomy Provisions")
abline(reg = reg5, col = "red")
dev.off()

reg6 <- lm(polity4_polity_score ~ reg_aut_dum, data = reg_data_complete)
reg6_tex <- texreg::texreg(reg6, include.ci = FALSE)
reg6_tex
plot(x = reg_data_complete$reg_aut_dum, y = reg_data_complete$polity4_polity_score)
abline(reg = reg6)

reg_full_tex <- texreg::texreg(list(reg1, reg5, reg6), 
                              mfrow = TRUE, 
                              omit.coef = "as.factor", 
                              include.ci = FALSE) 

reg_full_tex
```

# Other Calculations
```{r}
# Percentage of ethnically fractionalized states
psp_eth <- psp %>%
    dplyr::mutate_if(is.numeric, round, digits = 3) %>%
    dplyr::filter(qog_fe_etfra > median(psp$qog_fe_etfra, na.rm = TRUE))
pct <- length(unique(psp_eth$country)) / length(unique(psp$country)) * 100
pct

# Summary table
vars <- psp[, c("polity4_polity_score", "ucdp_cumulative_intensity", "qog_hum_trust", "dpi_auton", "qog_fe_etfra")]
cap <- "Summary Statistics"
reporttools::tableContinuous(vars = vars, cap = cap, longtable = FALSE)

```