---
title: "tjbrailey_data_analysis"
subtitle: "POLI 191A/B"
author: "Thomas Brailey"
date: "29/09/2019"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
```

# Load Data
```{r}
# Load PSP data, created in tjbrailey_wrangle_data.Rmd.
psp <- rio::import(paste0(here::here(), "/data/tjbrailey_psp_clean.csv"))
psp <- psp[,-1]
variable.names(psp)
```

# Averages 
```{r}
wvs_avg <- psp %>%
  dplyr::group_by(country) %>%
  dplyr::filter(any(!is.na(wvs_A124_neighbors))) %>%
  dplyr::summarize(avg = mean(wvs_A124_neighbors, na.rm = TRUE))

seg_aut_yr <- psp %>%
  dplyr::group_by(country) %>%
  dplyr::filter(any(!is.na(wvs_A124_neighbors))) %>%
  dplyr::tally(idc_auton == 1) %>%
  dplyr::mutate(n = (n / ((max(psp$year) - min(psp$year)) + 1) * 100 ))

wvs_seg_aut <- dplyr::left_join(seg_aut_yr, wvs_avg)

plot1 <- ggplot(wvs_seg_aut, aes(x = n, y = avg)) +
  geom_point() + 
  geom_smooth()
plot1
```

# Linear Regression
```{r}
lm1 <- lm(ucdp_cumulative_intensity ~ idc_auton, data = psp)
lm2 <- lm(ucdp_cumulative_intensity ~ idc_auton + year, data = psp)
lm3 <- lm(ucdp_cumulative_intensity ~ idc_auton + as.factor(year) + as.factor(country), data = psp)
lm4 <- lm(ucdp_cumulative_intensity ~ idc_auton + as.factor(year) + as.factor(country) + qog_gle_gdp, data = psp)
lm5 <- lm(ucdp_cumulative_intensity ~ idc_auton + as.factor(year) + as.factor(country) + qog_gle_gdp + qog_wbgi_pve, data = psp)
lm6 <- lm(ucdp_cumulative_intensity ~ idc_auton + as.factor(year) + as.factor(country) + qog_gle_gdp + qog_wbgi_pve + other_provis, data = psp)
summary(lm1)
summary(lm2)
summary(lm3)
summary(lm4)
summary(lm5)
summary(lm6)
```

# Logit 
```{r}
logit1 <- glm(ucdp_cumulative_intensity ~ idc_auton + year + as.factor(country),
                  data = psp, 
                family = binomial(link = "logit"))
logit1_predicted <- plogis(predict(logit1, psp))

Zelig::summary(logit1)

```


# Cox Regression
```{r}
cx1 <- survival::coxph(formula = survival::Surv(year, ucdp_cumulative_intensity) ~ idc_auton + country, data = psp)
summary(cx1)
```