---
title: "tjbrailey_var_explore"
subtitle: "POLI 191A/B"
author: "Thomas Brailey"
date: "27/09/2019"
output: html_document
---

```{r setup, include=FALSE}
#rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
```

# Load Data
```{r}
# Load PSP data, created in tjbrailey_wrangle_data.Rmd.
psp <- rio::import(paste0(here::here(), "/data/tjbrailey_psp_clean.csv"))
```

# Exploration of Core Consociational Provisions
```{r}
# Exploring consociationalism.

# States that employ mutual veto provisions.
psp %>% 
  dplyr::filter(idc_mveto == 1) %>%
  dplyr::distinct(country)

# States that employ grand coalition provisions.
psp %>%
  dplyr::filter(idc_gcman == 1 & idc_gcimp == 1) %>%
  dplyr::distinct(country)
 
# States that employ proportionality/
psp %>%
  dplyr::filter(dpi_pr == 1 | 
                  dtd_proportional == 1) %>%
  dplyr::distinct(country)

# States that employ segmental autonomy.
psp %>%
  dplyr::filter(idc_auton == 1) %>% 
  dplyr::distinct(country)
```

# Exploration of Segmental Autonomy
```{r}
# idc_auton missingness/summary.
auton_sum <- psp %>%
  dplyr::select(country, year, idc_auton) %>%
  dplyr::group_by(idc_auton) %>%
  dplyr::summarize(summary = n())

# States that have employed segmental autonomy provisions. 
seg_states <- psp %>%
  dplyr::filter(idc_auton == 1) %>% 
  dplyr::distinct(country) %>%
  dplyr::pull(country)

seg_states_dat <- psp %>% 
  dplyr::filter(country %in% c(seg_states))

# States that have, between 1975 and 2010, employed segmental autonomy provisions.
seg_imp <- seg_states_dat %>%
  dplyr::filter(idc_auton == 0) %>%
  dplyr::distinct(country) %>%
  dplyr::pull()

seg_imp_dat <- psp %>%
  dplyr::filter(country %in% c(seg_imp))
```

# Visualizing Segmental Autonomy Implementation
```{r}
gp1 <- ggplot(seg_imp_dat, aes(x = year, y = idc_auton)) +
  geom_point() +
  facet_wrap(~ country) + 
  labs(x = "Year",
       y = "Segmental Autonomy 
       (1 = Provision Implemented, 0 = Provision Not Present)",
       title = "Implementation of Segmental Autonomy Provisions") + 
  theme_bw()
gp1

ggsave(gp1, filename = paste0(here::here(), "/vis/seg_auton_implement.png"), units = "in",
       width = 11, height = 7)
```

```{r}
# Subdivisions of Segmental Autonomy.
subed <- psp %>%
  dplyr::filter(idc_subed == 1) %>%
  dplyr::distinct(country, year)

subtax <- psp %>%
  dplyr::filter(idc_subtax == 1) %>%
  dplyr::distinct(country, year)

subpolice <- psp %>%
  dplyr::filter(idc_subpolice == 1) %>%
  dplyr::distinct(country, year)

fedunits <- psp %>%
  dplyr::filter(idc_fedunits == 1) %>%
  dplyr::distinct(country, year)

author <- psp %>%
  dplyr::filter(dpi_author == 1) %>%
  dplyr::distinct(country, year)
```

# Additional Checks
```{r}
# Number of World Value Survey responses by country.
wvs_miss <- psp %>%
  dplyr::filter(!is.na(wvs_A124_neighbors))
```
