---
title: "Segmental Autonomy in Mali and Niger"
author: "Thomas J. Brailey"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    fig_crop: yes
    keep_tex: no
    number_sections: true
    citation_package: biblatex
bibliography: psp.bib
header-includes:
  - \usepackage[english]{babel}
  - \usepackage[utf8]{inputenc}
  - \usepackage{amsmath}
  - \usepackage{graphicx}
  - \usepackage{physics}
  - \usepackage{float}
  - \usepackage{tocloft}
  - \usepackage{inputenc}
  - \usepackage{setspace}
  - \usepackage{tabularx}
  - \usepackage{lipsum}
  - \usepackage{listings}
  - \usepackage{wrapfig}
  - \usepackage{mathtools}
  - \usepackage{lscape}
  - \usepackage{rotating}
  - \usepackage{epstopdf}
  - \usepackage{hyperref}
  - \usepackage[backend=biber,citestyle=authoryear, autocite=footnote, doi = false, url = false, isbn = false]{biblatex}
  - \geometry{letterpaper, portrait, margin=1in}
  - \addbibresource{psp.bib}
  - \hypersetup{colorlinks = false, linkbordercolor = {white}, citebordercolor = {white}, urlbordercolor = {white}}
  - \lstset{language=R, basicstyle=\small\ttfamily,stringstyle=\color{DarkGreen},otherkeywords={0,1,2,3,4,5,6,7,8,9},morekeywords={TRUE,FALSE},deletekeywords={data,frame,length,as,character}, keywordstyle=\color{blue}, commentstyle=\color{DarkGreen}}
  - \renewcommand{\cfttoctitlefont}{\hfill\Large\bfseries}
  - \renewcommand{\cftaftertoctitle}{\hfill\hfill}
  - \renewcommand{\cftloftitlefont}{\hfill\Large\bfseries}
  - \renewcommand{\cftafterloftitle}{\hfill}
  - \renewcommand{\cftlottitlefont}{\hfill\Large\bfseries}
  - \renewcommand{\cftafterlottitle}{\hfill}
fontsize: 14pt
---

\pagenumbering{arabic}

\doublespacing

\abstract

\newpage

\tableofcontents

\newpage

\section{Introduction}
In 2018, the warring parties in South Sudan signed the Revitalized Agreement on the Resolution of the Conflict in the Republic of South Sudan (R-ARCSS). This document re-establishes a transitional government, a truth commission, and outlines the general provisions of the new government. Among those provisions, the agreement calls for the recognition of thirty-two counties---drawn to accommodate the various ethnic groups in the state---and grants them substantial autonomy.\footcite{intergovernmental_authority_on_development_agreement_2015, vhumbunu_reviving_2019} The people of South Sudan, having been in the midst of ethnically-driven conflict since 2013, view this agreement with cautious optimism. Though a similar reserve is shared by signatories of the agreement and international observers, many believe that the extent of the agreement's inclusivity, and its significant local and regional ownership, are likely to create peace following its implementation.\footcite{vhumbunu_reviving_2019, njoroge_status_2019} 

South Sudan, in proposing the implementation of regional autonomy for their thirty-two counties, joins a growing number of ethnically diverse states in employing power-sharing institutions. These broadly defined institutions are designed to address a number of issues associated with emerging democracies, especially those with salient ethnic cleavages.\footcite{horowitz_ethnic_1985, lijphart_consociational_1969, esman_management_1973, nordlinger_conflict_1972} First, power-sharing is designed to accommodate ethnic group demands through devolving power to subnational factions. Second, and often as an alternative to devolution, power-sharing can help integrate regional groups into a central government. This often takes the form of coalition cabinets or reserved executive positions for certain groups. In both cases, power-sharing is a tool to abate conflict, lessen tensions among politically salient ethnic or minority actors, and ultimately help states transition into full democracy. While, at present, uncertainty surrounds the political trajectory of South Sudan, we see power-sharing presented as a plausible solution to conflict in an ethnically fractious society. 

The case of South Sudan highlights two issues associated with the power-sharing literature. First, it is difficult for scholars to draw meaningful conclusions on the effectiveness of power-sharing, consociationalism, and the other forms of nation-building, when the concepts themselves are subjective and contested. This conceptual disparity hinders our ability to aggregate results and generate cumulative findings.\footcite{dunning_information_2020} Second, there is a paucity of micro-level analysis focusing on the disaggregated provisions of power-sharing institutions. We do not know, for example, whether certain individual arrangements are more likely to cause peace than others nor in what ways these arrangements work. This paper sets out to address and reconcile these gaps in the literature by first analyzing the substantive effects of an individual provision of power-sharing and second, by establishing a framework which will allow for cumulative and more generalizable findings moving forward. 

Broadly speaking, power-sharing falls into two camps. Firstly, when certain power-sharing provisions are embedded in, or amended into, a constitution, we have what is generally understood to be consociational democracy. States that are often cited as being consociational in nature include the Netherlands from 1917 to 1967, Cyprus from 1960 to 1963, and Lebanon from 1943 to 1975, and from 1989 onwards.\footcite{andeweg_consociational_2000, lijphart_consociational_1977, picard_political_2000} Secondly, non-consociational power-sharing provisions can be written into a peace agreement following a conflict. This is what the more recent literature focuses on.\footcite{strom_inclusion_2017, graham_safeguarding_2017, jarstad_words_2008, mukherjee_why_2006} Power-sharing in these instances are implemented via accord and address civil tensions in a given state. Agreements can be, as Hartzell and Hoddie (2003, 2007) suggest, political, economic, territorial, or military in nature. While consociational democracy differs conceptually from power-sharing institutions found in peace accords, they serve the same purpose---that is, to ensure peace within socially diverse states---and their underlying provisions often overlap.

One provision that warrants particular analysis is segmental autonomy. Sometimes referred to as regional autonomy, it is a form of decentralization that grants specific powers to minority, geographically constrained, groups.\footnote{It is worth noting that segmental autonomy is \textit{not} the same as federalism. For an in-depth study of the relationship between regional autonomy and federalism, see \cite{lluch_autonomism_2012}.} Given that segmental autonomy has a far broader conception than, say, mutual veto, there are markedly more polities that exhibit some form of segmental autonomy over time. Perhaps more importantly, regional autonomy appears in several authors' typologies of power-sharing, allowing us to transcend these constraining conceptualizations. 

Segmental autonomy was first conceptualized by Arend Lijphart as a provision allowing groups to "transcend cleavages and to join in a common effort with the elites of rival subcultures".\footcite[216]{lijphart_consociational_1969} In essence, by granting minority groups some level regional autonomy, cross-cutting social cleavages, and officially recognizing these newly autonomous group, the provision serves as a concession to those groups and thus abates tension and conflict. Lijphart expands upon this idea in later works, highlighting the importance of the minorities’ rule over itself, and adds that segmental autonomy can be implemented in a territorial or non-territorial federation, or a political system that allows for substantial delegation to segmental groups.\footcite{lijphart_consociational_1977, lijphart_non-majoritarian_1985} 

Through analyzing the disaggregated forms of power-sharing, we are able to ask new questions about the nature of power-sharing. Specifically, I ask two questions pertaining to segmental autonomy and its effect on prolonged peace, democratization, and social trust. Building off of existing studies, I theorize that segmental autonomy operates in three distinct ways: through proliferating political focal points; through targeting concessions toward regional minorities; and by allowing regional groups to serve as checks and balances on the central government. Given these mechanisms, I hypothesize that the implementation of segmental autonomy exerts a positive effect on prolonged peace, a state’s level of democracy, and the reduction of tension within an ethnically fractionalized society. Existing studies of power-sharing and consociationalism produce mixed results regarding its effectiveness, though many qualitative case-study analyses seem to point to the possibility that power-sharing in certain circumstances can be effective. By developing a framework in which to analyze the provisions themselves, I will be able to uncover which provisions are most effective at causing peace and why. I add to my initial hypothesis by looking at the effects of segmental autonomy when employed alongside other power-sharing components. This hypothesis is borne from Norris’s (2008) argument that power-sharing is moderated by multiple provisions, insofar as the impact of power-sharing is magnified when more provisions are implemented.

I apply this theoretical framework using a paired case study of Mali, which implemented regional autonomy in 1999, and Niger, which did not engage in any form of decentralization. 

\section{Conceptualizing Power-Sharing}
The concept of consociationalism was promulgated by Arend Lijphart in his seminal work "Consociational Democracy". Lijphart develops his own typology of existing democratic structures, stating that "[c]onsociational democracy means government by elite cartel designed to turn a democracy with a fragmented political culture into a stable democracy," and outlining several favorable conditions of consociationalism’s success.\footcite[216]{lijphart_consociational_1969} The core provisions include segmental autonomy, mutual veto, grand coalition, and proportionality, though Lijphart's typology has expanded since its inception. It has been met with intense scrutiny over the years, with particular attention paid to its tautological nature, extensive and fluid conditions for success, and various country case studies where consociationalism has apparently failed.\footcite{andeweg_consociational_2000, bogaards_favourable_1998, seaver_regional_2000, tull_hidden_2005} Debates surrounding consociationalism seem to serve as a microcosm for the debates on power-sharing writ large as Andeweg (2000) states that "the level of abstraction of many contributions to (and critiques of) consociationalism is rather low, perhaps because the theory has largely been developed inductively from empirical case studies".\footcite[531]{andeweg_consociational_2000} Existing studies range from the necessity of consociationalism in ethnofederal polities,\footcite{lijphart_consociational_1969, lijphart_consociational_1977, oleary_debating_2005} to the modes which purportedly ensure a successful implementation of a peace pact,\footcite{walter_committing_2002, walter_explaining_2003, hartzell_institutionalizing_2003, hoddie_civil_2003, mukherjee_why_2006} to the tautological nature, and irrelevance, of consociational and power-sharing practices.\footcite{andeweg_consociational_2000, bogaards_favourable_1998, roeder_sustainable_2003} Some go as far as to argue that consociationalism serves as a platform for fundamentalism and may actually provoke ethnic conflicts, though the pro-consociational camp make the same argument for integrationist policies.\footcite{oleary_debating_2005} There is clearly a great deal of disagreement over power-sharing’s effectiveness and whether it is required at all. 

As mentioned, perhaps the most striking issue associated with the concept of power-sharing is its fluidity. There is no clear differentiation between consociationalism, power-sharing, power-dividing, and partition. There seems to be four broad camps regarding power-sharing design: those who focus on power-sharing as a form of democracy;\footcite{barry_consociational_1975, lijphart_consociational_1974, norris_evidence_2008, steiner_research_1981} those who focus on power-sharing through peace agreements and policy;\footcite{hartzell_institutionalizing_2003, hartzell_crafting_2007, mukherjee_why_2006} and those who favor integrationist versus accommodating provisions. Within all four groups, there is disagreement on what constitutes power-sharing, and what its main areas of focus are and should be. The purpose of power-sharing is also disputed, with many authors using different formulations of the dependent variable; one author who claims that power-sharing is effective because it abates conflict is disputed by another who argues it is ineffective as it does not include all ethnic identities in a government. Of the recent quantitatively-oriented literature, the authors highlight entirely different conceptions of power-sharing.\footcite{hartzell_institutionalizing_2003, hartzell_crafting_2007, graham_safeguarding_2017, jarstad_words_2008, mattes_fostering_2009, strom_inclusion_2017, walter_committing_2002} Hartzell and Hoddie (2003, 2007) suggest that multidimensional power-sharing institutions, that is, those institutions with several power-sharing provisions, are more likely to see positive results regarding democratization and cessation of conflict than fewer, though fail to explore in depth the provisions themselves.\footcite[325-332]{hartzell_institutionalizing_2003}

More pertinent to my own study, there is a slowly growing body of literature that focuses on the comparison and reconciliation of the various power-sharing datasets and the consolidation of the various conceptions of power-sharing institutions and political systems. There is also at least one study on an individual provision of power-sharing. Given the data that exist, studying the provisions of power-sharing is problematic. As Ansorg et al. (2013) note, of the two-hundred and fifty-seven datasets on institutions and conflict in divided societies, "[t]ransparency was an issue for 28.4 percent of [them]".\footcite[12]{ansorg_mind_2013} Many do not have codebooks, there are few sources referenced, and detailed operationalization is lacking. As such, any attempt to compare findings of the success of power-sharing, as well as the actual contents of the power-sharing institutions, is challenging. The issues of vague data are less pertinent with the large country-level datasets such as the Database of Political Institutions (DPI), Varieties of Democracy (V-DEM), and Quality of Governance (QOG), but are far more prevalent in datasets create for the purpose of academic articles.\footnote{With the latter, in some cases, links and references to data used in the paper are broken, and codebooks unfinished, and one dataset used in a successful book on power-sharing institutions has over sixty-nine percent missingness.} Further, Binningsbø (2013) compares recent quantitative and causal approaches to power-sharing, arguing that while the designs are similar, "they use somewhat different reasoning explaining the relationship" between power-sharing, peace, and democratization.\footcite[101]{binningsbo_power_2013} While it is undoubtedly necessary for nuanced approaches to be taken in order to better understand the causes, outcomes, and conditions of power-sharing, these studies exist in their own defined universes, making comparison and cross-validation somewhat challenging. Strøm et al. (2017) note a similar issue: "[o]nce we recognize that powersharing can be disaggregated in such ways, however, it is entirely possible that its different components do not always work in concert or reinforce one another".\footcite[6]{strom_inclusion_2017} Though they agree with Binningsbø (2013) on the possibility of disaggregation, the roles of the provisions, and their overlap with the various conceptions of power-sharing, is not explored further. 

One recent paper by Ram and Strøm (2014) uses this disaggregated approach to power-sharing. They focus on analyzing one type of consociational provision---mutual veto---and their findings are both enlightening and warrant further exploration into the other provisions of consociational democracy and power-sharing agreements. Their initial findings seem to undermine, or at least disagree with, the current debate on consociationalism. While the debate focuses on consociationalism as either a panacea for fractious societies or an inevitable roadblock to democratic survival, Ram and Strøm (2014) find that, in the case of mutual veto, the provisions of consociationalism are simply not common. "[M]utual veto provisions are a rare form of power-sharing," they suggest, and only eleven polities have implemented such provisions between 1975 and 2010.\footcite[345]{ram_mutual_2014} Descriptively, states that have employed mutual veto provisions have experienced mildly reduced conflict rates, yet, somewhat counterintuitively, mutual veto provisions are "most common in relatively prosperous and institutionally stable societies".\footcite[355]{ram_mutual_2014} It is interesting, then, that Lijphart and others would be so adamant of the essentiality of mutual veto provisions in consociational democracy in spite of their minimal prevalence and their emergence in non-conflictual democracies. We can assume that the success of consociational systems, and other power-sharing arrangements, must emerge from some sort of interaction effect, or perhaps by a particularly salient, as of yet unexplored, provision.

The small sample of mutual veto states means that statistical analysis is not a feasible option. One advantage of studying segmental autonomy in particular is that there are notably more observations to study, lending itself to both case study and large-N analyses. This will be explored further in the next section.  

\subsection{Conceptualizing Segmental Autonomy}
I apply Ram and Strøm's (2014) disaggregating approach to the provision of segmental autonomy. The concept of segmental autonomy has expanded vastly since its conception. Far from the vague parameters of Lijphart’s earlier work, segmental autonomy can now be further disaggregated into religious, ethnic, and racial autonomy, educational autonomy, and, as mentioned, is defined as being laterally separated from federalism. Norris’s (2008) and Kelly’s (2019) meta-analyses both do an excellent job in reconciling the literature on consociational theory and developing a theoretical framework to better understand the favorable conditions of segmental autonomy. Kelly (2019) cites the work of Steiner (1981) and Halpern (1986) in establishing the core requirements of autonomy necessary for consociationalism, namely, distinguishable cultural groups with their own identities and their own political organization, political relevance, within-group marriage, and a widely perceived legitimacy within the state.\footcite[30]{kelly_power-sharing_2019, steiner_research_1981, halpern_disorderly_1986} Both authors reach a similar conclusion regarding power-sharing and inclusive constitutional design. Kelly (2019) suggests that, when adopting a qualitative approach, segmental autonomy can be "conducive to stability in plural societies," though regression models suggest that segmental autonomy can be "destabilizing".\footcite[3]{kelly_power-sharing_2019} Norris (2008), too, states that "power-sharing arrangements are the best chance of success for sustaining democracy" but that it should be "interpreted cautiously, with many qualifiers" given the mixed results from state to state.\footcite[222]{norris_what_2008} Much like the broader discussion of power-sharing and consociationalism, a firm conclusion on the efficacy of individual provisions is frustrated by country-specific characteristics and contestation over the implementation of these provisions. That said, a more fine-grain understanding of the provisions of power-sharing is necessary to evaluate power-sharing as a response to ethnically divided and conflictual states.

It is perhaps because of the broadly-encompassing nature of this provision that segmental autonomy is cited in several different and competing power-sharing typologies. Subnational autonomy, as it is coined, can be found in Charron’s (2009) discussion of vertical power-sharing in ethnofederalist states. When assessing the saliency of ethnofederal arrangements, they suggest that "the more diverse the state, the stronger the predicted benefit that an ethnofederation produces in terms of [quality of governance]".\footcite[600]{charron_government_2009} Regional autonomy is a core provision in territorial power-sharing, according to Hartzell and Hoddie (2007). Various forms of "subnational authority" are facets of Strøm et al.’s (2017) so-called dispersive power-sharing. Perhaps most interestingly, regional autonomy is also cited as a component in partition, according to Berg and Ben-Porat (2008), Roeder and Rothchild (2005), and Kuperman (2004), the former arguing that "[f]ederal autonomy extends beyond consociationalism towards partition".\footcite[33]{berg_introduction:_2008} The latter conception is particularly interesting, as partition is often presented as an alternative to power-sharing though they both share autonomy as a provision.\footcite{berg_introduction:_2008, roeder_sustainable_2003}

Before moving forward, it is worth clarifying some conceptual definitions. First, I conceptually define power-sharing provisions as the underlying mechanisms within a constitution or peace agreement that allow for military, political, economic, social, and territorial inclusion and accommodation for a state's minority groups. Second, I define segmental autonomy in line with Lijphart (1969, 1977), Norris (2008), and Kelly’s (2019) definition. That is, minority groups, with government-recognized autonomy over specific and salient political issues. For the purposes of this paper, subnational units must have \textit{de jure} regional autonomy to be included in my analysis. Though it will be discussed more in Chapter 5, this conception of segmental autonomy can be operationalized using a dichotomous measurement, where a state that employs regional autonomy will have a value of 1, and 0 otherwise. 

\subsection{Partition, Power-Dividing, and Ethnofederalism}
It is worth acknowledging the concepts of partitioning and power-dividing as they relate to the literature on institutions of peace. Though less of the literature focuses on these two concepts, they are inextricably linked to power-sharing (in that they are often presented as an alternative to power-sharing) and exhibit similar terminological discrepancy. Proponents of power-dividing as an alternative to power-sharing include Roeder and Rothchild (2005), who define power-dividing institutions as those that "stress the importance of civil liberties that limit government, separation of powers that create multiple majorities, and checks and balances that limit each majority".\footcite[52]{roeder_sustainable_2003}. Conversely, Hartzell and Hoddie (2007) talk about the successes of power-sharing and power-dividing institutions as similar or interchangeable institutions.\footcite[150-152]{hartzell_crafting_2007} What is more, when one breaks down both power-dividing and the various conceptions of power-sharing, one finds that many of the individual provisions are strikingly similar. Civil liberties, multiple majorities, checks and balances, and separation of powers are indicative of Roeder and Rothchild’s (2005) conception of power-dividing, though are also present in Strøm et al.’s (2017) conception of inclusive power-sharing, and Hartzell and Hoddie’s (2003, 2007) conception of political power-sharing. 

Kuperman makes two arguments that further muddy the debate on power-sharing versus alternative forms of institutionalizing peace. Firstly, they argue that there are "six cases of \textit{true} power sharing" based on the presence of regional autonomy, peace enforcement, disguised victory, non-ethnic schisms, and a pause in fighting.\footcite[emphasis added]{kuperman_power_2006} Secondly, they argue in favor of partition---partition \textit{de jure}, adjusted borders, and or regional autonomy---in the case of the conflicts in Bosnia. Specifically, they argue that regional autonomy would be the most effective method; "close to de facto partition, without the prize of independence. It is a compromise solution".\footcite{kuperman_power-sharing_2006} However, regional or segmental autonomy is a key provision in several different conceptions of power-sharing in peace agreements and in political systems. Though partition is purported to be a "a solution of ‘last resort’" and as a "meeting point between the needs for self-determination and territorial expression", the provisions by which it is deemed to be successful are shared by an opposing institution: power-sharing.\footcite[32]{berg_introduction:_2008, waterman_partitioned_1987} Given the overlap between the provisions of not just the forms of power-sharing, but also other methods of institutionalizing peace, it seems logical to assess which of these provisions are most common, and which are most effective.

Ethnofederalism is another dimension of power-sharing that incorporates regional autonomy. Despite the name, ethnofederalism is more closely related to regional or segmental autonomy than it is to federalism; ethnofederal arrangements are designed to devolve power among minority groups within specific geographic jurisdictions.\footcite{roeder_where_2007, roeder_ethnofederalism_2009} Roeder is highly sceptical of ethnofederal arrangements, suggesting that by privileging certain ethnic identities, states run the risk of escalating conflict into "acute nation-state crises".\footcite[206]{roeder_ethnofederalism_2009} Though perhaps providing short-term relief to conflictual and ethnically divided states, Roeder argues that proponents of ethnofederalist arrangements fail to account for the long term implications of making concessions to politically marginalized groups. These implications range from regional minorities making more demands, to increased conflict rates, to complete secession of that region. However, like the provision of mutual veto, ethnofederalism is relatively uncommon. From 1945 through to today, there have been eleven states that have generally been understood to be ethnofederal, including Czechoslovakia, Nigeria, Uganda, and India.\footcite{lake_policy_1996} We also see regional autonomy and decentralization viewed as a detriment to democratic progress in the context of ethnofederalism, yet seen as a potential solution to conflictual states in the context of partition.\footcite{roeder_sustainable_2003, roeder_where_2007, roeder_ethnofederalism_2009} In sum, the efficacy of these broadly-conceptualized peace institutions are heavily disputed. That provisions such as segmental autonomy are common across many of these concepts of power-sharing, we may be able to better understand what exactly leads to peace by disaggregating the broad definitions and studying the individual mechanisms therein. 

\section{Theory and Hypothesis}
Given that segmental autonomy is relatively common across countries, and continues to be implemented in conflictual societies today, governments and citizens must consider the provision effective to some degree. I hypothesize that states employing segmental autonomy provisions along with other provisions of power-sharing, either through peace accord or constitutional reform, are more likely to experience reduced intergroup tensions, prolonged peace, and ultimately, democratization. But how does the implementation of regional autonomy in a ethnically fractious and politically unstable state lead to peace? In other words, what are the underlying mechanisms that allow segmental autonomy to work in such a state? Building off of existing studies, I suggest that regional autonomy works in three distinct ways: through proliferating political focal points, through targeting concessions to regional minorities, and by allowing regional minorities to serve as checks and balances on the central government. In an ethnically fractionalized state, where certain groups may have faced powerlessness or discrimination, the implementation of regional autonomy---be it through regional elections, educational authority, linguistic autonomy, or otherwise---can be seen as a concerted effort by the central government to bring about peace. Assuming this basic logic, I lay out a more nuanced theory and causal mechanism, before presenting my core hypotheses. 

The causal chains that justify the implementation of segmental autonomy in ethnically diverse states come from the work of Lijphart (1969), Nordlinger (1972), and Esman (1973). They argue that provisions such as regional autonomy and other forms of power-sharing serve to "reduce the long-range political salience of communal solidarities," though each embed this outcome in a slightly different framework.\footcite[55]{esman_management_1973} Moving beyond these broad theoretical arguments, I identify segmental autonomy operating in three distinct---but often overlapping---ways. 

\subsection{Proliferation of Focal Points}
Regional autonomy increases the number of political focal points in a state. By proliferating the number of autonomous regions, the central government can reduce the possibility of any one faction having power over another. As a result, the likelihood that one group feels disadvantaged or oppressed by another is reduced. Increasing the number of political focal points not only reduces inter-faction tensions, it also takes pressure off of the central government as the newly autonomous regions can act independently, such as by implementing their own tax, education, or language policies. Demands are thus less likely to be aimed at the central government, given that matters related to the ethnic group are in the hands of the subnational political bodies. We see the proliferation of subnational units in states such as Uganda and Nigeria as examples of a central government’s attempt to reduce the political salience of any given ethnic or regional group. The dispersive aspect of regional autonomy might reduce ethnic conflict and grievances by "tak[ing] the heat off of a single focal point".\footcite[598]{horowitz_ethnic_1985} In dispersing political focal points and creating new outlets for political competition, regional autonomy might also allow the central government to consolidate power. Consolidation is particularly useful for new governments and governments in the midst of a conflict or political crisis. In these instances, regional autonomy essentially serves to draw attention away from the government, giving politicians manoeuvrability and allowing the central government to tighten their grip on the state through reconfiguring their power.\footcite{seely_political_2001, gasper_decentralization_1989}

\subsection{Targeted Concessions to Regional Minorities}
The implementation of segmental autonomy provisions can serve as a concession to marginalized ethnic groups, potentially reducing the risk of conflict involving the central government or other ethnic groups. It is sometimes referred to as "cooptation".\footcite{seely_political_2001} In order to avoid the breakup of a state or a conflict, regional autonomy can abate political instability by meeting the needs of a dissatisfied group. As above, this can manifest as the group exerting substantial control over regional policymaking. One common argument against regional autonomy as a concession is that it opens the floodgates to more serious demands such as secession, and may increase ethnic violence. Roeder makes a convincing argument against autonomy as it relates to ethnofederalism, stating that "[e]thnically homogeneous cantons that divide ethnic communities may encourage inter-regional competition within ethnic groups," strengthening regional identities and discouraging state consolidation.\footcite[219]{roeder_ethnofederalism_2009} While this is clearly a potential threat, two points are worth noting. Firstly, secession itself is incredibly rare, and, whether successful or unsuccessful, secession is unlikely to be directly attributed to increased demands in autonomous locales.\footcite{mehler_consociationalism_2013, roeder_secessionism_2014} Secondly, segmental autonomy is designed in part to balance any regional power disparities, and so additional demands are likely to come from groups who perceive themselves as being left behind. As Lluch (2012) argues, autonomism succeeds because of its hybridity and multiplicity: "it can perfectly balance its anti-federalist stances with its grounding in the federalist principle of multiple levels of government within the same state apparatus, complemented by its anti-secessionism stance".\footcite[155]{lluch_autonomism_2012} There is clearly a mixed track record with dispersive forms of power-sharing and ethnofederalism. As such, this warrants empirical analysis of regional autonomy in order to establish what exactly makes decentralization effective or harmful in ethnically diverse states. 

\subsection{Checks and Balances on the Central Government}
Segmental autonomy is not just dispersive in nature. In ethnically fractionalized states in particular, segmental autonomy is most effective when it allows ethnic minorities to act independently of the central government while also giving that group some level of representation and control in the central government. Regional elections are a perfect example of such a mechanism. In implementing regional elections for geographically distinct ethnic minorities, previously powerless or discriminated groups are able to elect representatives of the same ethnic group who might then implement policies appropriate to the groups' needs. These elected members also serve as checks on the central government, thus legitimizing the regime. In granting more autonomy to salient regions, the central government might be perceived as more democratic and inclusive. Of course, attributing perceptions of democracy to the integration of regional actors into a central government is challenging to establish, but we do see decentralization improving public perceptions of democracy in various countries.\footcite{escobarlemmon_does_2014, world_values_survey_world_2007} Beyond just perception, legitimization may in fact improve democracy given that regional actors, if integrated successfully, can serve as meaningful checks and balances on the central government.

\subsection{Interactions Between Provisions}
Lastly, in employing segmental autonomy alongside other consociational provisions, one can balance out the potential pitfalls of one mechanism with another. For example, the "accommodating" provisions of mutual veto and segmental autonomy, which grant additional powers to minority political actors may, as mentioned, entrench ethnic identities and potentially lead to conflict. By implementing more inherently "integrative" measures---those designed to break down ethnic identities and force cooperation---such as coalition cabinets and proportional representation, the potential for deepened ethnic divisions are reduced. Both Hartzell and Hoddie (2007) and Norris (2008) speak to the effectiveness of using multiple complementary power-sharing provisions. Given this, I expect to see any positive effects on my outcome variables either maintain a positive relationship or experience an increase in the relationship when incorporating multiple dimensions of power-sharing in addition to segmental autonomy.

With these theoretical mechanisms and assumptions in mind, I present my two core hypotheses:

\singlespacing

\textbf{H\textsubscript{1}}: \textit{Ethnically diverse states that employ segmental autonomy provisions, either through peace accord or constitutional reform, will experience reduced intergroup tensions, prolonged peace, and democratization.}

\bigskip

\textbf{H\textsubscript{2}}: \textit{Ethnically diverse states that employ segmental autonomy provisions along with other provisions of power-sharing, either through peace accord or constitutional reform, will experience reduced intergroup tensions, prolonged peace, and democratization.}

\doublespacing

In proliferating political focal points, responding to regional group demands, and integrating regional minorities into the central government, segmental autonomy can serve as an effective remedy to ethnically diverse states. In implementing multiple power-sharing mechanisms, the weaknesses of segmental autonomy may be counterbalanced by more inherently inclusive provisions such as coalition cabinets and proportional representation. Conversely, if my results do not confirm my hypothesis, I will fail to reject the null: 

\singlespacing

\textbf{H\textsubscript{Null}}: \textit{There will be no significant relationship between the implementation of segmental autonomy provisions and the reduction in intergroup tensions, prolonged peace, and democratization in ethnically diverse states.}

\doublespacing

\subsection{Alternative Mechanisms}
I also acknowledge some alternative theoretical arguments and potential threats of segmental autonomy. As mentioned, a common criticism of segmental autonomy is that it could lead to more aggressive demands, increased conflict, and potentially secession. The separation of groups along ethnic lines could reduce intergroup interactions to the point that prejudice and scapegoating may become the norm.\footcite{kelly_power-sharing_2019} Keller and Smith (2005) share a similar concern to Kelly (2019) in that segmental autonomy may go beyond political decentralization and group self-determination, instead exacerbating intergroup tensions and oppositional identities, and incentivizing more extreme concessions by the central government. They suggest that "[t]he long-term implications of [subnational autonomy] are unclear, but in the short term there has been a tendency for increased demands for further autonomy among distinct groups within regions".\footcite[240]{keller_obstacle_2005} While these are issues that undoubtedly need to be considered during the planning and implementation of regional autonomy provisions, there are a number of issues with these claims. First, segmental autonomy is seldom a completely dispersive institution. As we have seen, provisions such as regional elections are both accommodative and integrative in nature, and so it is unlikely that ethnic groups will be partitioned to the point that they are unable to interact with one another. Second, Keller and Smith (2005) use Ethiopia to argue against the effectiveness of segmental autonomy. Ethiopia is an interesting case given that there were calls for secession and hostile intergroup relations well before the implementation of ethnofederalism in 1991.\footcite{vogt_integrating_2015} Moreover, much of the ethnic conflict that followed the regional autonomy in 1991 arose because of the incomplete nature of its implementation, rather than the provisions therein. Certain ethnic groups were still discriminated against, and the central government committed acts of violence against these marginalized groups.\footcite{vogt_integrating_2015} It is therefore important to supplement case studies with more rigorous empirical methods to avoid misleading extrapolation. In any case, ethnically fractionalized states with marginalized populations will, in some respect, benefit from increased autonomy and state recognition. The degree to which this is the case will be analyzed in Chapter 5.

\section{Controlled Case Study: Segmental Autonomy in Mali and Niger}
Having established the theoretical mechanisms through which segmental autonomy functions, how can these theories be tested in the real world? By process-tracing two well-matched countries, we are able to contextualize our theoretical mechanisms of autonomy and provide a plausible account of its effectiveness. The contiguous states of Mali and Niger provide an instructive qualitative comparison of the effects of regional autonomy and allow us to do just that. 

Prior to Mali's implementation of regional autonomy in 1999, Mali and Niger bear striking similarities at baseline that warrant further investigation and comparison: they have similar population sizes and GDP; share the same political system; and have both been subject to French colonial rule. More importantly, both states have a significant Tuareg population within their borders and similar ethnic group structures. According to their respective censuses, Mali comprises 50\% Mande, 16\% Fula, 13\% Voltaic, and 10\% Tuareg while Niger consists of 55\% Hausa, 21\% Zarma-Songhai, and 9\% Tuareg. Though interethnic relationships between most groups are peaceful, the Tuaregs---who are more regionalized in Mali and Niger---have historically faced discrimination. The Tuareg are traditionally nomadic pastoralists, though in Mali and Niger they are largely regionally consolidated in the north. The Tuareg are linguistically and culturally distinct; they speak Tamasheq and, unlike other ethnic groups in Mali and Niger, are matrilineal.\footnote{A map showing the geographic spread of the Tuareg population across Mali and Niger can be found in the appendix.} In addition to economic marginalization, the Tuareg have faced cultural discrimination such as the prohibition of nomadism in Niger and a lack of representation in the central government in both states.\footcite{ibrahim_political_1994} The Tuareg's violence toward the central government, and their demands for increased autonomy and representation, can be attributed to their shift between powerlessness and discrimination post-independence.\footcite{vogt_integrating_2015}

Since independence in 1960, the two countries have had similar political experiences. From military and one-party rule for most of the 1960s and 1970s, to various coups d’état against autocratic leaders, to democratic reforms throughout the 1990s, Mali and Niger's stories have been of ethnic tension and regional instability. The two countries diverged significantly in 1999 when Mali, in response to growing ethnic tensions, implemented regional autonomy in the form of regional elections. Following similar ethnic violence and a coup, Niger opted for the inclusion of Tuareg members as ministers in a coalition government, and explicitly avoided regional autonomy provisions for the Tuareg population.\footcite{minorities_at_risk_project_minorities_2009} In not implementing regional autonomy, various reports suggest that relations between the Niger government and the Tuareg ethnic population have declined, especially when compared to the relative peace and amicability between the Tuareg and the Malian government following autonomy. These well-matched cases allow for the use of John Stewart Mill's "method of difference" which compares different outcomes associated with an independent variable across two cases.\footcite{mill_system_1843} In Mali and Niger, the two states are also well-matched on the outcome variables prior to the implementation of segmental autonomy, where data exist. For example, both Mali and Niger ranked relatively low on the PolityIV index following independence and prior to democratization in the 1990s, and we see the two states diverge in purported levels of democracy and social trust ratings after 1999. For the other measures that these states have been matched on, Mali and Niger exhibit similar trends from independence through to the end of the century. This will be elucidated later in the section, but these similar characteristics and parallel trends on the variables and outcomes of interest provide justification to process-trace the impacts of segmental autonomy. 

\begin{table}[!htbp]
    \centering
    \setlength{\tabcolsep}{10pt}
    \renewcommand{\arraystretch}{1.5} 
    \resizebox{\textwidth}{!}{\begin{tabular}{|l|c|c|}
            \hline
            \textbf{Country}                &   \textbf{Mali}  &  \textbf{Niger}  \\ 
            \hline
            Regional Autonomy?              &   Yes            &  No              \\
            \hline
            Population (1999, millions)     &   10.6           &  10.9            \\
            \hline
            Tuareg \% of Population (2001)  &   10             &  9.3             \\
            \hline
            GDP (1999, billion USD)         &   3.4            &  2.0             \\
            \hline
            Ethnic Fractionalization (1999) &   0.8            &  0.6             \\
            \hline
            Area (million sq. km.)          &   1.2            &  1.3             \\
            \hline
            Former French Colony?           &  Yes             &  Yes             \\
            \hline 
            Political System                &  Unitary semi-presidential republic & Unitary
            semi-presidential republic  \\
            \hline
    \end{tabular}}
    \caption{Country Characteristics Around Mali's Decentralization}
\end{table}

Prior to achieving autonomy in 1999, the Tuareg had been pressuring the Malian government to decentralize decision-making and grant them greater economic freedom. Though the Malian government were concerned that the Tuareg might push for a complete secession from the state, they refused to grant the Tuareg people regional autonomy or any form of power-sharing provision.\footcite{vogt_integrating_2015} Students and civil servants began protesting in January of 1991 as a result of persistent economic decline and oppressive rule.\footcite{unknown_malis_1991, unknown_leader_1991} Exacerbated by Tuareg pressures to devolve powers, these protests culminated in a coup d’état in March of 1991 against authoritarian leader Moussa Traoré. The following year saw the introduction of peace accords granting the Tuareg some level of regional autonomy.\footcite{humphreys_senegal_2005} Though intended to abate tensions between the central government and the ethnic groups in Mali, the peace accords were not fully implemented until 1999 when the first Tuareg regional elections were held.\footcite{keita_conflict_1998, seely_political_2001} Prior to the regional elections, rates of politically-motivated conflict between the Tuareg, the central government, and other minority ethnic populations, remained high. In the years following the \textit{de facto} implementation of regional autonomy, conflict rates and fatalities appeared to decrease. The Ethnic Power-Relations Atlas (EPR) anecdotally remarks that following regional autonomy in the north east, conflict rates markedly decreased, especially within the Tuareg region.\footcite{vogt_integrating_2015} Similarly, the Minorities at Risk Project notes that, despite a recent history of rebellion and violence, Mali's Tuareg population are "unlikely to engage in large-scale violence in the near future" as the government has provided, through decentralization "more openings for conventional and nonviolent political activity".\footcite{minorities_at_risk_project_minorities_2009}

The Tuareg in Niger faced similar discrimination post-independence. As in Mali, the Tuareg were economically marginalized and effectively unable to participate in government decision-making. In 1993, two years after especially intense violence between the military government and the Tuareg population, a power-sharing government was established in the form of a coalition cabinet. Though some government positions were held by Tuareg politicians, they were quickly sacked and detained.\footcite{krings_marginalisation_1995} It was not until 1994 that the Tuareg---though still in the midst of violence with state army---were successfully integrated into the governing coalition. While their inclusion pointed to reduced tensions, 2004 saw the removal (and execution) of Tuareg officials in government, effectively ending the coalition cabinet model of power-sharing. Again, the Tuareg were rendered powerless, and in 2007 a Tuareg rebellion broke out against the government demanding more representation. Interestingly, the 2007 Tuareg rebellions occurred in both Mali and Niger almost simultaneously, but where the violence in Mali focused on the government's failure to implement economic reforms, the violence in Niger was attributed to their political exclusion.\footcite{bertelsmann_stiftung_niger_nodate}

Why did the Nigerien government refuse decentralization? Pons (1993) argues that the regions populated by the Tuareg happen to be rich in uranium, which, during the 1990s, accounted for about 80\% of Niger's exports. The central government did not wish to relinquish their most economically viable region to an ethnic minority and adversary and thus sought integration through alternative power-sharing provisions.\footcite{krings_marginalisation_1995, pons_probleme_1993} These provisions were never fully realized and, as a result, the Tuareg population in Niger---throughout the numerous democratic and authoritarian transitions since 1999---are purported to exhibit several risk factors for rebellion and increased violence.\footcite{minorities_at_risk_project_minorities_2009} 

Recall that segmental autonomy might reduce conflict through serving as a concession to marginalized and dissatisfied ethnic groups, and legitimize a regime by giving minority groups more policymaking power and political representation. There exists evidence of autonomy's positive cooptive effect as, immediately after the implementation of autonomy, Tuareg rebels willingly "handed over mortars, anti-tank mines and grenade launchers" to the central government, who then destroyed these weapons.\footcite{unknown_tuareg_2008} This ceremonial event shows that the implementation of regional autonomy was a concession made by the central government to the Tuareg minority in a bid to reduce conflict. Empirically, little work has been conducted to assess whether the number of casualties has changed since the implementation of autonomy in Mali, though data from the Armed Conflict Location and Event Data (ACLED) indicates that the implementation of segmental autonomy was a contributing factor to the reduction of conflict.\footcite[,unpublished manuscript]{raleigh_introducing_2010, brailey_after_2019} Perhaps more importantly, regional autonomy also served to legitimize the Tuareg, who were represented in the central government following the regional elections in 1999. Evidence suggests that perceptions of democracy improved following the implementation of regional autonomy and several rounds of successful regional elections in northern Mali.\footcite{world_values_survey_world_2007}

In process-tracing the political histories and trajectories of post-independence Mali and Niger, it is clear that Niger has faced greater political unrest as a result of dictatorial leadership (such as the constitutional crisis of 2009), economic and environmental factors, and other factors unrelated to the power-sharing institutions themselves. However, it is undeniable that much of the ethnic unrest and violence stems directly from the central government's inability to meaningfully integrate or accommodate the Tuareg population. This includes their failure to grant regional autonomy to the Tuareg after several decades of Tuareg demands. While the political future of the Tuareg in Mali is uncertain and conflict persists as a result of underlying economic grievances, the level of violence between ethnic minorities and the central government is far less severe than in Niger.

As with the empirical conceptions of regional autonomy, \textit{prima facie} evidence from Mali and Niger should be interpreted with caution and two caveats are in order. First, though this paper seeks to understand the impacts of regional autonomy across three dimensions---conflict, social and intergroup trust, and democratization---evidence and measurements for the latter two variables in the two states are scarce. Afrobarometer data exists for Mali in 2000, and suggests that there is broad support for democracy and a general satisfaction with democratic institutions.\footcite{afrobarometer_afrobarometer_1991} While these data support the findings of existing studies, that no pre-autonomy measures of these variables exist makes establishing causal or correlative relationships essentially impossible. Second, we see that these states are facing a plethora of dynamic political issues, making it difficult to isolate and attribute a single causal mechanism. To elucidate, if regional autonomy is in fact reducing intergroup tensions, there exists little data to analyze ethnic group trust for the Malian population in and around 1999, and even if the data did exist it would be difficult to isolate regional autonomy as the main cause, given that there are several other country-specific factors operating and interacting with autonomy and its implementation. It is worth mentioning the resource curse as one such country-specific factor in Niger. A large body of literature suggests that, because Niger relied on uranium as its primary export, the state is inherently more likely to face political instability and autocratic shifts.\footcite{mehlum_institutions_2006, sachs_curse_2001} While this may have contributed to Niger's overall instability, Tuareg violence occurred irrespective of resources; their focus was solely on achieving more political influence. In any case, evidence from Mali and Niger, and the seemingly positive impacts of regional autonomy in the former state, warrants further investigation as to the substantive effects of regional autonomy in ethnically fractionalized polities. 

\section{Discussion}

\section{Conclusion}

\newpage

\addcontentsline{toc}{section}{References}
